"""Generate all 3 training datasets as XLSX files"""
import pandas as pd
import os

os.chdir(os.path.dirname(os.path.abspath(__file__)))
out = "training/datasets"
os.makedirs(out, exist_ok=True)

# ============================================================
# SENTIMENT DATASET - 500 samples (~167 per class)
# ============================================================
sentiment_data = [
# POSITIVE (~167)
("Gila sih ini aplikasi keren bgt! Auto langganan premium gw mah", "Positive"),
("Baru nyobain fitur barunya dan wow... finally ada yg ngerti user experience", "Positive"),
("@brand_indonesia thanks bgt udah fast response! masalah gw kelar dalam 5 menit doang", "Positive"),
("Nonton konser @musisi tadi malam... speechless. sound system jernih, lighting gila", "Positive"),
("Indomie telor + es teh manis = combo maut yg ga pernah gagal", "Positive"),
("Abis pake skincare lokal ini 2 minggu, muka glowing parah. murah lagi, bye produk impor", "Positive"),
("Gais ini real review ya, delivery cepet bgt padahal lagi tanggal merah. seller the best!", "Positive"),
("Baru join gym sebulan udah turun 4kg. instrukturnya supportif bgt, ga nyesel daftar", "Positive"),
("Thread ini wajib dibaca buat yg mau mulai investasi saham. sederhana, actionable", "Positive"),
("finally sinyal 5G masuk ke daerah gw. download 1GB cuma 10 detik woy", "Positive"),
("Timnas main gila tadi malem! finally mainnya enak diliat, pressing ketat, passing akurat", "Positive"),
("Yg bilang kalo kopi lokal kalah sama impor blm nyobain ini kayaknya. single origin Kerinci is life", "Positive"),
("Ada yg udah coba BRT Trans Semarang rute baru? bersih, tepat waktu, AC dingin", "Positive"),
("Barusan claim garansi barang elektronik, prosesnya smooth bgt. ga pake ribet, langsung ganti", "Positive"),
("documentary series barunya GILA BAGUS BANGET. production quality hollywood, cerita nendang", "Positive"),
("Diinterview user researcher startup ini, 30 menit doang dapet voucher 150rb. ga nyangka", "Positive"),
("fotografer wedding budget 5jt hasilnya kayak 20jt. natural, semua momen ke-capture", "Positive"),
("Jadi inget dulu pas kuliah di Jogja. best years of my life. orangnya ramah2, makanan murah", "Positive"),
("Rejeki anak saleh, abis dapet beasiswa full buat S2. akhirnya impian kesampean", "Positive"),
("Liat startup lokal tembus series A funding. bangga bgt sama anak bangsa", "Positive"),
("Thread cara bikin CV yg lolos ATS system ini lifesaver. udah terapin, akhirnya dapet interview", "Positive"),
("Goodbye comfort zone, hello growth. baru resign dari toxic workplace, never felt this relieved", "Positive"),
("Yg bilang cari kerja susah, coba ikutin tips dari thread ini. networking is the key", "Positive"),
("Kucing stray yg gw adopt 6 bulan lalu skrg udah sehat dan gemoy. worth all the vet bills", "Positive"),
("Abis donate ke yayasan pendidikan, laporan penggunaannya transparan bgt", "Positive"),
("Baru sadar kalo healing ga harus mahal. naik gunung 1 jam dari kota, view sunrise mantap", "Positive"),
("driver gocar tadi pagi insightful bgt ngobrolnya. banyak belajar dari pengalaman dia", "Positive"),
("Review jujur: laptop ini performanya kenceng bgt buat coding. ga panas, baterai tahan 8 jam", "Positive"),
("Udh setahun pake bank digital ini, ga ada masalah sama sekali. transfer gratis, app ga lemot", "Positive"),
("Mural di sudut jalan Braga ini keren bgt. kota butuh lebih banyak street art kayak gini", "Positive"),
("Ibu gw baru lulus kursus barista, skrg buka coffee shop kecil di garasi. laku banget", "Positive"),
("Ada rekomendasi buku bagus nih buat yg lagi quarter life crisis. baca bab 3 langsung nangis", "Positive"),
("vaksinasi di puskesmas deket rumah cepet dan ramah. ga perlu nunggu lama, petugasnya informatif", "Positive"),
("Bosen sama menu catering kantor, akhirnya pesen dari @katering_sehat. enak bersih porsi ga pelit", "Positive"),
("KALO NGGAK PERCAYA SAMA KUALITAS PRODUK LOKAL, LIAT NIH REVIEW GW. MIND BLOWING", "Positive"),
("Dari semua marketplace, ini satu2nya yg pengembalian barangnya gampang. ga perlu debat", "Positive"),
("Abis marathon nonton film2 Indonesia di platform ini. kualitas sutradara lokal udah level internasional", "Positive"),
("Berkat thread cara atur keuangan 50/30/20, akhirnya punya dana darurat. thanks random stranger di X", "Positive"),
("Tempat coworking ini vibesnya cozy bgt. free flow coffee, internet kencang, komunitasnya welcoming", "Positive"),
("Ada yg ngerti ga kenapa langit sore ini oren banget? indah bgt sampe berhenti di jalan cuma buat foto", "Positive"),
("Baru selesai baca buku Atomic Habits. this book changed my life. simple but powerful", "Positive"),
("thanks buat flash sale jam 12 malem! dapet kitchen set setengah harga. istri seneng gw seneng", "Positive"),
("Yang kemaren stress karena jomblo, skrg gw sadar... jomblo itu kesempatan buat upgrade diri", "Positive"),
("Pelatihan coding gratis dari @dicoding ini materinya daging banget. mentornya sabar", "Positive"),
("Nemu playlist Spotify yg cocok buat deep work. productivity boosted 200% since gw pake ini", "Positive"),
("Renovasi rumah 2 bulan akhirnya selesai. kontraktornya recommended bgt. tepat waktu sesuai budget", "Positive"),
("Yg bilang cewe gabisa teknis... temen gw cewe barusan juara 1 hackathon. you go girl!", "Positive"),
("Thread edukasi politik ini harusnya dipake buat mata pelajaran di SMA. bahasa sederhana ga bias", "Positive"),
("Workshop public speaking 2 hari ini game changer. skrg pede presentasi di depan direksi", "Positive"),
("kolaborasi ini jenius. kirim paket 2 jam nyampe. game changer buat UMKM lokal", "Positive"),
("Baru liat ada startup yg bikin solar panel murah buat rumah tangga. keren bgt ini masa depan energi", "Positive"),
("Tadi ada bapak2 parkir motor bantuin nyebrangin nenek2... Indonesia masih ada yg baik2 ternyata", "Positive"),
("Abis nonton pertunjukan teater di TIM Jakarta. produksinya luar biasa. talenta seniman kita ga main2", "Positive"),
("Kursus bahasa asing online ini sistemnya immersive bgt. 3 bulan gw udah bisa ngobrol casual", "Positive"),
("Dapet mentor di tempat kerja baru, beda banget rasanya. diajarin disupport dikasih feedback membangun", "Positive"),
("Bakso Mas Joko di deket Stasiun Depok ini juara dunia. kuahnya berasa rempah, baksonya gede2", "Positive"),
("Guys app pencatatan keuangan lokal ini underrated bgt. UI simple, bisa scan struk otomatis, gratis", "Positive"),
("Yg bilang Jakarta isinya stress doang blm kenal sisi buruknya. sabtu minggu car free day... healing gratis", "Positive"),
("Perjuangan menabung 2 tahun buat DP rumah akhirnya lunas. walaupun rame dikit, ini rumah gw", "Positive"),
("Baru donate buku bekas ke perpustakaan desa. responnya positif bgt, anak2 pada seneng", "Positive"),
("Tips buat yg sering anxiety: journaling works. 10 menit tiap pagi, mental health improve drastically", "Positive"),
("lo kemaren kasih refund karena konser diundur, prosesnya gampang. ga kaya vendor sebelah", "Positive"),
("akhirnya dapet sertifikasi UI/UX dari Google. 6 bulan belajar tiap malem, paid off", "Positive"),
("Soto Ayam Cak To di Surabaya adalah soto terenak yg pernah gw makan. dan gw udah cobain ratusan soto", "Positive"),
("Ini template Notion buat nge-track progress belajar. gratis, simple, works perfectly", "Positive"),
("Review mic budget 200rb buat podcast: ini di luar ekspektasi. kualitas suara jernih, noise cancelling ok", "Positive"),
("Panti asuhan ini bener2 ngurusin anak2 dengan serius. fasilitas lengkap, pendidikannya diperhatiin", "Positive"),
("Bersyukur banget punya partner yg supportive. ga toxic, saling ngisi, bisa diskusi apapun", "Positive"),
("Baru pindah dari Android ke iPhone... dan wow, the ecosystem is real. semua sync seamlessly", "Positive"),
("app kalian update terbaru keren bgt. itinerary planner otomatisnya helpful banget", "Positive"),
("Ada yg tau ga resto hidden gem di Bandung? yg jualnya di atas bukit gitu view kota bagus", "Positive"),
("Beli split AC merk lokal di marketplace, pemasangan cepet dan free. dinginnya cepet, hemat listrik", "Positive"),
("Yg masih ragu sama karir di tech... coba aja dulu. gw lulusan sastra, skrg fullstack developer", "Positive"),
("Review HP mid range 3 jutaan ini: kamera setara flagship, baterai awet, layar AMOLED", "Positive"),
("Semua yg gw pelajarin dari thread crypto ini akhirnya berbuah manis. paham cara diversifikasi investasi", "Positive"),
("Jangan sepelein power networking di LinkedIn. karena koneksi LinkedIn, gw dapet opportunity remote", "Positive"),
("Abis pake jasa deep clean rumah, hasilnya kinclong sempurna sampe ke celah2. 300rb puas banget", "Positive"),
("Liat anak2 down syndrome perform dance di acara amal... gw nangis. their spirit is unmatched", "Positive"),
("Vaksinasi rabies di klinik hewan deket rumah cuma 100rb. dokter checkup manteeeeng", "Positive"),
("Nemu aplikasi yg bisa convert PDF ke Excel dengan akurat. no more manual input data 3 jam", "Positive"),
("Ada yg pernah coba restoran Padang di Jl. Veteran? rendangnya tuh lembut bgt sampe ambyar", "Positive"),
("Tempat gym yg tarifnya 150rb per bulan ini: bersih, alat lengkap, ada kelas yoga", "Positive"),
("konsultasi dokter 5 menit langsung nyambung. resep dikirim ke apotek deket rumah. revolusi healthcare", "Positive"),
("Thread singkat cara membuat konten LinkedIn yg engage. udah gw terapiin, impressions naik 300%", "Positive"),
("Adopt dont shop. 3 anjing rescue yg gw pelihara skrg jadi guardian terbaik buat anak2", "Positive"),
("Baju thrifting 50rb ini kualitasnya setara brand mahal. bahan masih bagus, jahitan rapi", "Positive"),
("Review tiket.com: mereka bantu gw banget pas penerbangan delayed. dikasih hotel gratis + makan", "Positive"),
("Yg bingung mau olahraga apa, coba boulder climbing. seru, full body workout, komunitasnya asik", "Positive"),
("Nemu aplikasi journaling yg ada fitur mood tracking + statistik. ternyata pola tidur pengaruh ke mood", "Positive"),
("Petugas KRL hari ini baik bgt. ada ibu2 jatoh, langsung dibantuin sampe dicariin tempat duduk", "Positive"),
("weekend ini diskon sampai 80 persen beneran. dapet sepatu branded 200rb. datang pagi biar ga kehabisan", "Positive"),
("Kalo diitung2, 5 tahun terakhir aplikasi ini bantu gw dapetin banyak insight dari data", "Positive"),
("Rekomendasi toko kacamata murah di Melawai ini jujur bgt. lensa tipis harganya masuk akal", "Positive"),
("Ada yg nyari vendor souvenir pernikahan? ini recommended bgt. custom design gratis, produksi cepet", "Positive"),
("Seneng liat perubahan kebijakan publik yg terakhir ini. akhirnya ada yg denger suara rakyat", "Positive"),
("Thread ini ngebantu gw lulus wawancara teknikal di big tech company. ngajarin systematic problem solving", "Positive"),
("Skill yg dipelajari dari thread #belajarcode ini kepake di kerjaan gw skrg. terima kasih internet", "Positive"),
("Gatau ini app lokal apa kagak, tp fitur AI nya pinter bgt translate bahasa daerah", "Positive"),
("Yg lagi di Bali, mampir ke Tegallalang pagi2. sebelum rame turis, suasananya mistis tapi damai", "Positive"),
("Untuk pertama kalinya, tim e-sports Indonesia juara dunia. gw ga bisa berenti nangis", "Positive"),
("Ada startup yg bikin baterai daur ulang murah buat motor listrik. masa depan transportasi cerah", "Positive"),
("Pameran lukisan di Galeri Nasional minggu ini gratis. karya2nya menyentuh, kurasi tematik", "Positive"),
("Alhamdulillah akhirnya lunas juga KPR setelah 10 tahun. rasanya bebas banget", "Positive"),
("Bakso aci di deket kampus ini enak parah. pedesnya nampol, porsinya gede, murah lagi", "Positive"),
("Pengen banget kasih tau kalian... ini sunscreen lokal murah tp ga bikin whitecast sama sekali", "Positive"),
("Ojol driver tadi pagi ini the real MVP. hujan deres tetep anterin gw ke kantor tepat waktu", "Positive"),
("Kalian yg pada struggle sama procrastination, coba deh Pomodoro + Forest app combo. life changing", "Positive"),
("Event startup weekend kemaren inspiring banget. ketemu founder2 hebat, networking ngalir terus", "Positive"),
("Jujurly ini layanan streaming film lokal makin bagus. katalog makin lengkap, subtitle akurat", "Positive"),
("Kalo lo lagi di Bandung wajib cobain batagor di Kingsley. porsinya jumbo, kuah kacangnya nendang", "Positive"),
("Ini dia thread cara bikin portofolio UX researcher dari nol. step by step, ada template gratis", "Positive"),
("Berkat kursus ini, istri gw yg tadinya IRT skrg jadi freelancer sukses dgn penghasilan sendiri", "Positive"),
("Smart plug 50rb ini works perfectly. bisa kontrol lampu dr hape, timer otomatis, hemat listrik bgt", "Positive"),
("Seriously, thread soal mental health ini semua orang harus baca. destigmatize therapy", "Positive"),
("Review honest: robot vacuum 2jutaan ini performanya setara Roomba. nyedot debu sampe ke pojokan", "Positive"),
("Resign dr job toxic adalah keputusan TERBAIK dalam hidup gw. skrg kerja remote, gaji 2x lipat", "Positive"),
("Thread soal parenting ini ngebantu gw banget sebagai new dad. tipsnya praktis, ga judgemental", "Positive"),
("Speaker Bluetooth lokal 300rb ini suaranya jernih bass nendang. tahan air lagi, bisa dibawa ke pantai", "Positive"),
("Pelatihan barista gratis dari dinas pariwisata ini membuka jalan karir baru buat gw. thank you!", "Positive"),
("Literally ini thread paling bermanfaat di X sepanjang 2024. setiap poinnya daging semua", "Positive"),
("Berkat rekomendasi kalian di X, gw nemu tailor yg jahitannya rapih, harga terjangkau, hasil presisi", "Positive"),
("Ada yg udah nyobain matcha latte di kafe pojokan Blok M? enak parah, authentic, ga terlalu manis", "Positive"),
("Wajib follow akun ini kalo lo pengen ngerti politik Indonesia tanpa bias. analisisnya tajem dan berimbang", "Positive"),
("Review: standing desk rakitan 1.5jt ini kokoh, motor adjustment smooth, cable management rapi", "Positive"),
("Mie Ayam Pak Kumis di deket UI ini LEGENDARIS. dari jaman gw kuliah sampe skrg rasanya konsisten", "Positive"),
("Kalo lo freelance designer, wajib baca thread negosiasi rate ini. gw terapin, income naik 50%", "Positive"),
("Akhirnyaaa dapet juga tiket Coldplay. walaupun war ticket ampe berdarah2, worth it", "Positive"),
("Thread cara bikin sourdough starter ini detail banget. hari ke-7 akhirnya jadi juga rotinya", "Positive"),
("Backpack lokal 350rb ini kualitasnya bersaing sama brand luar. waterproof, laptop compartment empuk", "Positive"),
("Buat yg nyari jastip Korea terpercaya, rekomen akun ini. fast response, harga fair, packing aman", "Positive"),
("Bubur Ayam Barokah buka jam 6 malem sampe subuh. recommended buat yg laper tengah malem", "Positive"),
("Ada yg tau komunitas board game di Jakarta? gw baru join, seru bgt. weekly meetup, inclusive banget", "Positive"),
("Review: TWS lokal 200rb ini ANC nya works surprisingly well. nyalain musik, dunia langsung hening", "Positive"),
("Thread cara bikin personal brand di LinkedIn ini emas. gw terapin, recruiter yg nge-DM duluan", "Positive"),
("Hari ini productive bgt. beresin 5 task besar, olahraga, masak, masih sempet baca buku. feels great", "Positive"),
("Air purifier rakitan lokal ini efektif bersihin udara. debu berkurang drastis, alergi gw mereda", "Positive"),
("Ternak lele di lahan sempit? bisa. gw ikutin thread ini, panen pertama 50kg. lumayan buat tambahan", "Positive"),
("Kalau lo suka kopi, Wajib cobain manual brew V60. ritual pagi yg bikin tenang dan nikmat", "Positive"),
("Checkout @threadreaderapp unroll dulu deh sebelum baca thread2 penting. save time, tetep dapet insight", "Positive"),
("Kopi Kenangan emang ga ada matinya. harga 18rb, rasa konsisten, gerai dimana2. local brand goals", "Positive"),
("Workshop menulis 2 hari ini bener2 transformatif. skrg gw pede submit artikel ke media nasional", "Positive"),
("Yg bilang cari jodoh susah, coba deh ikutin komunitas lari. sehat, dapet temen, siapa tau jodoh", "Positive"),
("Review: tablet 2jt buat gambar digital. pressure sensitive, layar responsive, layak buat pemula", "Positive"),
("Abis 6 bulan rutin pagi2 minum air lemon + jahe, badan berasa enteng, jarang sakit. give it a try", "Positive"),
("Based on true story: gw yg tadinya nganggur, skrg jadi digital marketer setelah ikutin thread ini", "Positive"),
("Mie Gacoan level 5 pedesnya nampol bgt. tapi nagih. wajib coba minimal sekali seumur hidup", "Positive"),
("Apreasiasi buat developer yg bikin app transportasi publik. finally ada realtime tracking akurat", "Positive"),
("Setelah sekian lama, akhirnya ada juga podcast Indonesia yg bahas sejarah dgn narasi menarik", "Positive"),
("Jangan remehin kekuatan cold email. 50 email gw kirim, 5 respond, 1 jadi klien. works!", "Positive"),
("Baru coba fitur AI di software editing foto, hasilnya natural bgt. ga kaya filter instagram jaman dulu", "Positive"),
("Salut sama Komunitas #SapuJagat yg bersihin sampah tiap minggu. aksi nyata, bukan cuma ngomong doang", "Positive"),
("Review motor listrik lokal: akselerasi halus, charging murah, fitur lengkap. future is electric", "Positive"),
("Ada yg tau ga resto all you can eat sushi murah di Jakarta? 150rb udah including sashimi. top", "Positive"),
("Thread ngerjain skripsi 6 bulan ini beneran works. gw ikutin step by step, lulus tepat waktu", "Positive"),
("Ngafe di cafe berkonsep perpustakaan ini enak bgt. tenang, wifi kenceng, buku bisa dibaca gratis", "Positive"),
("Review jujur: virtual office 300rb per bulan ini udah termasuk alamat prestisius + resepsionis", "Positive"),
("MasyaAllah tabarakallah... akhirnya bisa umrohin orang tua. perjuangan nabung 3 tahun terbayar", "Positive"),
("Kalau mau ngerti ekonomi makro dengan bahasa sederhana, follow akun ini. infografisnya ciamik", "Positive"),
("Sepatu lokal ini nyaman bgt dipake lari. cushioning empuk, breathable, design keren. proud local brand", "Positive"),
("Asuransi kesehatan swasta ini proses klaimnya cepet. 2 hari langsung cair. ga kaya yg lain", "Positive"),
("Hari ini dapet surat cinta dari pembaca blog gw. kecil2an tp bermakna. ini yg bikin semangat nulis lagi", "Positive"),
("Thread cara investasi reksadana untuk pemula ini Wajib disave. udah ada simulasi + kalkulatornya", "Positive"),
("Voucher belanja 100rb dari app ini beneran usable. no minimum purchase, no hidden terms", "Positive"),
("Sunrise di Bukit Sikunir Dieng itu magis. capek naiknya kebayar sama viewnya. Indonesia itu indah", "Positive"),
("Kursus menjahit online 3 bulan, skrg gw bisa bikin baju sendiri. hobi yg menghasilkan cuan", "Positive"),
("Kalau mau jadi content creator, saran gw: mulai aja dulu. perfect is enemy of done. thread ini panduannya", "Positive"),

# NEGATIVE (~167)
("Pelayanan di bank ini minggu ini buruk banget, ngantri sejam teller cuma 2", "Negative"),
("Janjinya next day delivery, udah 3 hari barang ga nyampe2. udah gitu CS susah dihubungi", "Negative"),
("udah 5x mention minta bantuan, dibalesnya template doang tanpa solusi. pathetic", "Negative"),
("Beli tiket konser di vendor, waktu checkout malah di kick. balik lagi eh harganya naik 2x lipat", "Negative"),
("Aplikasi mobile banking error terus dari pagi. mau transfer urgent ga bisa", "Negative"),
("Driver ojol tiba2 cancel padahal udah nunggu lama. katanya hujan padahal terang benderang", "Negative"),
("Barang yg dateng beda total sama foto. warna beda, ukuran beda, bahannya murahan bgt", "Negative"),
("Restoran hits di sosmed ternyata zonk. rasa biasa aja, porsi dikit, harga selangit. hype doang", "Negative"),
("Timnas dipermalukan lagi di kandang sendiri. pelatih harusnya mundur, ini udah bukan soal taktik", "Negative"),
("Internet provider ngaku speed 100Mbps, pas test cuma dapet 3Mbps. penipuan berkedok iklan", "Negative"),
("janji konsultasi 5 menit nyambung. gw nunggu 2 jam lebih. pas nyambung, dokternya cuma 2 menit", "Negative"),
("Harga sembako naik lagi, gaji ga naik2. menteri ekonominya tidur apa gimana sih?", "Negative"),
("Update aplikasi malah bikin hape panas dan boros baterai. please test dulu sebelum rilis", "Negative"),
("Beli makanan di food court, nemu lalat di kuah soto. lapor ke manajemen malah disuruh ganti menu doang", "Negative"),
("BPJS itu teorinya bagus, prakteknya sampah. antri 4 jam, diagnosa 5 menit, obat sering kosong", "Negative"),
("Government official caught korupsi lagi, tp hukumannya cuma ringan. penjara kok kayak hotel", "Negative"),
("Motor diparkir di basement mall, helm ilang. lapor security cuma dicatat doang", "Negative"),
("Janji kampanye tinggal janji. dulu bilang mau hapus kemiskinan, skrg malah makin miskin", "Negative"),
("Amazon lokal? jangan ngimpi. barang mahal, pilihan dikit, return policy ribet", "Negative"),
("Tuyul aja kalo ditabung makin berkembang, ini gaji gw makin menyusut karena inflasi", "Negative"),
("Liat thread orang flexing gaji 30jt per bulan. gw yg UMR cuma bisa gigit jari", "Negative"),
("Cosplay event kemarin kacau. tiket mahal, venue sempit, AC mati, artis tamu cancel mendadak", "Negative"),
("Kursus yg harganya 5jt ini materinya copy paste dari blog gratisan. scammer makin canggih sekarang", "Negative"),
("gocar gw dapet driver yg sambil telponan terus, nyetir ugal2an, ga pake seatbelt", "Negative"),
("Konser tahun ini line up bagus, sayang event organizernya amatir. sound system pecah, tiket double booking", "Negative"),
("Vendor IT di kantor ga becus. project molor 3 bulan, hasilnya buggy. tapi temen deket bos, ga dipecat", "Negative"),
("Twitter isinya bots semua sekarang. reply tweet artis isinya nitip sendal mulu. platform udah mati", "Negative"),
("Yang bilang kerja keras pasti sukses boong. gw kerja 12 jam sehari, weekends lembur, gaji masih UMR", "Negative"),
("Tempat wisata viral di TikTok ternyata zonk. air keruh, fasilitas rusak, HTM mahal. foto editan semua", "Negative"),
("Pertamina ngaku udah pake BBM Euro 4, tp udara Jakarta makin item. mungkin Euro 4 nya cm di spanduk", "Negative"),
("UMKM dihajar bertubi2 sama produk impor ilegal. pemerintah sibuk selfie, rakyat kecil makin mati", "Negative"),
("Beli hp bekas lewat sosmed, pas barang nyampe rusak. seller ilang, nomor ga aktif. trust issues", "Negative"),
("Fenomena FOMO bikin lo beli barang ga jelas. gw beli alat olahraga yg viral, skrg cuma jadi gantungan baju", "Negative"),
("Anak magang digaji murah, dimarah2in, disuruh kerja kayak kuda. katanya cari pengalaman. pengalaman apa?", "Negative"),
("Fitur baru di app ini useless. bikin berat app doang. developernya kaya ga pake appnya sendiri", "Negative"),
("Rapat 3 jam di kantor, outputnya cuma 1 keputusan: akan dibahas di meeting berikutnya. birokrasi sampah", "Negative"),
("Harga parkir di mall 5000 per jam. belanja sejam kena 5000, padahal udah belanja ratusan ribu", "Negative"),
("Komisi pemilu bikin website hasil pemilu yg down mulu. budget miliaran, kualitas server 500rb", "Negative"),
("Ganti provider internet, sales janjiin banyak hal. pas udah pasang, speed lemot, CS ga ada kabar", "Negative"),
("Pesawat delay 6 jam cuma dikasih snack kotak isi roti kering. kecewa bukan main", "Negative"),
("Beli barang di marketplace, seller ngaku barang original. ternyata kw super. report ke marketplace dibiarin", "Negative"),
("Modus penipuan baru: ngaku debt collector, nelpon keluarga, ngancem sebar data. lapor polisi ga ada kelanjutan", "Negative"),
("Pendidikan di Indonesia itu mahal tp ga berkualitas. buku cetak baru tiap tahun, bedanya cm ganti halaman", "Negative"),
("Pengalaman buruk di SPBU: isi bensin 100rb, indikator di motor cuma naik setengah. curang", "Negative"),
("Desain UI ini bikin mata capek. warna mencolok, font kecil, alignment acak2an", "Negative"),
("Jaman skrg semua pada flexing. yg kerja keras diem2. yg hasil korupsi pamer di sosmed. twisted world", "Negative"),
("Wifi kampus kenceng kalo ga dipake. pas butuh buat upload paper, lemotnya minta ampun. ironi", "Negative"),
("Food blogger ngasih rating 5 bintang buat resto yg jelas2 zonk. berapa sih dibayarnya?", "Negative"),
("Gara2 promo super murah, server down pas checkout. pas udah normal, barang abis. marketing jebakan", "Negative"),
("Anjing tetangga ngegonggong tiap malem, lapor RT ga ngefek. tidur gw hancur, produktivitas anjlok", "Negative"),
("Kualitas toilet bandara kita malu2in. masa bandara internasional, toiletnya bau pesing air mati tisu abis", "Negative"),
("Pinjol ilegal masih berkeliaran. temen gw diteror debt collector padahal udah bayar lunas", "Negative"),
("Mantan toxic muncul lagi setelah gw bahagia. ngechat pake akun burner. please move on I already did", "Negative"),
("Loker yg isinya mencari kandidat pengalaman 5 tahun untuk posisi junior. HR tolol atau sengaja?", "Negative"),
("Pedagang kecil digusur atas nama penertiban, tp pengusaha besar yg langgar aturan dibiarin", "Negative"),
("Beli skincare yg katanya BPOM approved. pas dicek nomornya palsu. merk abal2 pake endorser artis", "Negative"),
("pulsa kepotong tiba2 buat layanan yg ga gw aktifin. unsubscribe susah minta ampun. ini pencurian", "Negative"),
("Tiket pesawat mahal karena biaya avtur, tapi pas avtur turun, harga tiket ga turun", "Negative"),
("Interview kerja udah nyampe tahap user, di ghosting. ga ada kabar, ga ada email penolakan", "Negative"),
("Ujian online pake platform proctoring yg makan resource laptop gede. laptop i3 gw crash terus", "Negative"),
("Film Indonesia yg ceritanya cuma itu2 aja. horor digantungin jumpscare doang, komedi receh", "Negative"),
("Kalo pemilu doang yg langsung, kenapa kenaikan harga sembako ga bisa divoting?", "Negative"),
("Vendor photobooth di acara kantor zonk. alat rusak, print blur, operator ga responsif", "Negative"),
("Korban PHK disuruh jadi pengusaha, dikasih pelatihan 3 hari. emang bisnis itu segampang masak mie?", "Negative"),
("Tiket masuk tempat wisata mahal, tapi track hikingnya rusak, ga ada guide, toilet bayar lagi", "Negative"),
("Abis minum kopi di kafe viral, malah keracunan. lapor ke manajemen ga ditanggapi", "Negative"),
("Rekening tiba2 diblokir tanpa pemberitahuan. CS bilang sistem, ga bisa jelasin lebih detail", "Negative"),
("Diajak temen join MLM, dikasih presentasi panjang. intinya: lo bisa kaya kalo lo mau nipu temen2 lo", "Negative"),
("Beli barang flash sale, ternyata stok kosong tapi transaksi sukses. refund seminggu lebih", "Negative"),
("Polusi udara Jakarta memperpendek usia 5 tahun. solusi pemerintah? pindah ibu kota. bukan atasi, tapi kabur", "Negative"),
("Komentar di postingan sosmed isinya pada ngegas semua. diskusi sehat udah punah, diganti debat kusir", "Negative"),
("Korban penipuan online lapor polisi, malah disuruh nunggu 3 bulan. duit pelaku udah habis duluan", "Negative"),
("Update terms and conditions 20 halaman, disuruh agree. siapa yg baca? jebakan hukum legal", "Negative"),
("Co-founder startup ghosting tiba2, ninggalin utang. mentalitas founder lokal sampah", "Negative"),
("Lo udah loyalitas 5 tahun di kantor, tp kenaikan gaji cuma 3 persen. fresh graduate gajinya lebih gede", "Negative"),
("Makan di resto Padang, harganya ga jelas. ditanya berapa buk? dijawab nanti diitungin. pas bayar dirampok", "Negative"),
("Layanan kesehatan mental di Indonesia memprihatinkan. psikolog mahal, waiting list panjang, stigma kuat", "Negative"),
("Kencan online itu capek. match banyak, yg nyambung dikit. ghosting dimana2. jadi cat lady lebih damai", "Negative"),
("Kecewa berat sama brand lokal yg katanya support local. pas gw review jujur 3 bintang, langsung di-unfollow", "Negative"),
("Ada temen yg flexing di sosmed, padahal gw tau dia banyak utang. fake life, fake happiness", "Negative"),
("Toko langganan 3 tahun tiba2 naikin harga tanpa kasih tau. nota tetep segitu. kena tipu baru sadar", "Negative"),
("Perasaan gw makin jujur lo di dunia kerja, makin lo diinjak. yg naik jabatan tuh yg jilat", "Negative"),
("Thread Twitter isinya debat politik ga jelas. kedua kubu sama2 toxic, ga ada yg bener", "Negative"),
("Mental health gw hancur gara2 doom scrolling X tiap malem. harusnya udah stop kemaren", "Negative"),
("Akun2 gimmick cuma nyari engagement doang. quote retweet isi hujatan, konten orisinal nihil", "Negative"),
("Update terbaru app X malah bikin timeline chaos. algoritma baru ini nyusahin kreator kecil", "Negative"),
("Ya Allah capek banget liat timeline isinya flexing semua. pada pamer gaji pamer liburan pamer pasangan", "Negative"),
("Cancel culture di X udah keterlaluan. orang salah dikit langsung digeruduk, padahal belom tentu salah", "Negative"),
("udah 2 minggu nunggu refund, CS cuma bales pake bot. uang gw 500rb melayang gitu aja", "Negative"),
("Bikin thread bermanfaat sepi, bikin konten receh rame. platform ini rewarding kebodohan", "Negative"),
("Disini pada ngatain buzzword sosmed, giliran ditanya solusi diem semua", "Negative"),
("Beli iPhone lewat seller online, garansi resmi katanya. pas klaim, apple store bilang IMEI ga kedaftar", "Negative"),
("Percaya sama review online? semua bisa dibeli. gw udah kapok, lebih percaya omongan random di X", "Negative"),
("Lagi tren startup bangkrut, karyawan ga digaji 3 bulan. founder malah pamer investasi baru di sosmed", "Negative"),
("Pelayanan restoran ini sampah, waiter jutek, makanan lama, harga mahal, porsi dikit. ga worth it", "Negative"),
("Beli case HP custom, hasil printnya burem, bahan murahan. 150rb kebuang percuma", "Negative"),
("Janji manis tukang kredit, pas telat sehari langsung didatengin debt collector. manusia apa preman?", "Negative"),
("Sewa apartemen via agen, pas masuk banyak kerusakan ga disebutin. deposit ditahan tanpa alasan jelas", "Negative"),
("Internet mati 3 hari ga ada pemberitahuan. CS cuma minta maaf tanpa solusi. layanan publik darurat", "Negative"),
("Ngantri imigrasi 4 jam buat bikin paspor. kursi dikit, AC ga kerasa, staffnya lelet. memalukan", "Negative"),
("Beli susu formula bayi di marketplace, pas dateng expired tinggal 1 bulan. seller ga mau tanggung jawab", "Negative"),
("RT/RW setempat ga responsif. got mampet sebulan ga dibenerin, banjir terus. iuran jalan terus", "Negative"),
("Kualitas bimbel online ini jeblok. guru cuma baca slide doang, tanya jawab ga interaktif. harga mahal", "Negative"),
("Daftar gym setahun, bulan ke-3 tutup tanpa pemberitahuan. uang ga balik, owner kabur. hati2 gym abal2", "Negative"),
("Jasa arsitek mahal, gambar kerja ga jelas. tukang bingung, bangunan molor, budget over 50%. nightmare", "Negative"),
("Ini yg gw benci dari budaya kerja Indonesia: lembur ga dibayar, cuti ditolak, atasan semena2", "Negative"),
("Review: kursus data science 20jt, materi cuma teori doang, instruktur ga prepared. total scam", "Negative"),
("Beli minyak goreng curah di pasar, ehhh dicampur air. rakus bgt sih pedagang jaman sekarang", "Negative"),
("Ngajuin kredit KPR, prosesnya ribet ampun2an. bolak balik 10x disuruh lengkapin dokumen yg sama", "Negative"),
("Tukang servis AC yg direkomendasiin RT ternyata bukan teknisi beneran. malah ngerusakin makin parah", "Negative"),
("Warganet +62 itu terkenal toxic. komen di postingan atlet kalah isinya cacian semua. mana sportifnya?", "Negative"),
("Nonton bioskop premiere, penonton pada berisik, main HP, ngobrol. etika nonton di Indonesia nol besar", "Negative"),
("Temen dipinjemin duit 10jt, pas ditagih malah marah2. gw yg baik malah disalahin. kapok minjemin", "Negative"),
("Beli mobil bekas dari showroom, 2 minggu kemudian mesin jebol. katanya kondisi prima, ternyata aspal", "Negative"),
("Browsing di internet isinya clickbait semua. judul heboh, isinya kosong. mati aja tuh jurnalisme", "Negative"),
("Aduan ke pengadilan konsumen cuma disuruh mediasi. perusahaan bandel, konsumen dibiarin aja", "Negative"),
("Pesanan di restoran salah terus. 3x ganti masih aja salah. kasirnya main HP, dapurnya ga becus", "Negative"),
("Cicilan motor di leasing disita padahal telat 2 hari. kontraknya kejam, bunganya tinggi, ga manusiawi", "Negative"),
("Ngonten di YouTube direport orang ga jelas, langsung kena strike. appeal ditolak mentah2. unfair", "Negative"),
("Check in hotel jam 2 siang, kamar belum siap sampe jam 5 sore. resepsionis ga informatif, managernya ga ada", "Negative"),
("Dapet warisan keluarga malah jadi sengketa. saudara kandung sendiri saling sikut. duit hancurin segalanya", "Negative"),
("Ini kok pemda bangun taman ga jelas, tapi trotoar buat pejalan kaki hancur semua. prioritasnya kacau", "Negative"),
("Perusahaan tempat gw kerja bangkrut, pesangon ga dibayar. owner pindah ke luar negeri. buruh ditelantarkan", "Negative"),
("Loker palsu masih banyak berkeliaran. suruh transfer buat administrasi, abis itu lenyap. parah", "Negative"),
("Polusi suara dari tempat hiburan malem bikin warga sekitar stress. lapor polisi ga ada tindakan", "Negative"),
("Pembangunan apartemen di depan komplek bikin rumah retak2. developer ga tanggung jawab, pemerintah diem", "Negative"),
("Klaim asuransi kecelakaan ditolak dengan alasan mengada2. padahal udah bayar premi 3 tahun tanpa telat", "Negative"),
("Sewa PS untuk acara kantor, barang setengah rusak semua. padahal udah DP setengah. kecewa berat", "Negative"),
("Kena tipu travel agent abal2. transfer lunas, pas hari H travelnya ga ada. tabungan setahun lenyap", "Negative"),
("Isi bensin di SPBU, ternyata BBM oplosan. motor jadi brebet, servis mahal. oknum SPBU makin parah", "Negative"),
("Ghosted setelah 3 bulan hubungan intens. tiba2 ilang tanpa penjelasan. ini kejahatan emosional", "Negative"),
("Nilai ujian anak gw tiba2 anjlok. ternyata gurunya minta les privat berbayar biar nilainya dibagusin", "Negative"),
("Maling di kosan gasak laptop + hape. kosan ga ada CCTV, pemilik kos lepas tangan. setahun belum ketangkep", "Negative"),
("Event organizer amatir ngurusin acara amal. sponsor mundur, dana diselewengkan, acara gagal total", "Negative"),
("Layanan streaming film legal tapi kualitas videonya kayak VCD bajakan. buat apa bayar?", "Negative"),

# NEUTRAL (~166)
("Cuaca siang ini panas banget, mungkin 35 derajat", "Neutral"),
("Ada yg tau ga travel Jakarta Bandung yg paling murah?", "Neutral"),
("Lagi di dalem KRL, ada yg jualan Tisu Magic, perlukah?", "Neutral"),
("Hari ini gw males ngapa2in, cuma scroll X dari pagi", "Neutral"),
("Yang udah ujian CPNS gimana? soal susah apa gampang?", "Neutral"),
("Gw mau nanya dong, lebih baik beli mobil baru atau bekas ya?", "Neutral"),
("Mau nanya dong, SIM C perpanjang sekarang dimana ya?", "Neutral"),
("Baru nyobain mode dark di aplikasi X, enak sih di mata", "Neutral"),
("Ada yg ngerti cara claim asuransi perjalanan?", "Neutral"),
("Lagi nyari rekomendasi kado ultah buat cewe budget 150rb", "Neutral"),
("Lagi hujan gini enaknya ngopi sambil baca buku ya", "Neutral"),
("Kalian tim iPhone apa Android?", "Neutral"),
("Lagi bosen, ada rekomendasi series yg seru?", "Neutral"),
("Tadi siang liat ada kucing orange tidur di motor orang", "Neutral"),
("Ada yg tau jam operasional perpustakaan nasional?", "Neutral"),
("min, kalau kirim paket ke luar pulau estimasi berapa hari?", "Neutral"),
("Berapa lama ya proses klaim garansi laptop?", "Neutral"),
("Yang udah cobain restoran baru di mall X, worth it ga?", "Neutral"),
("Ada yg punya rekomendasi laundry sepatu murah di Jaksel?", "Neutral"),
("Buat yg freelance, cara nentuin rate gimana?", "Neutral"),
("Tadi siang makan di warteg, lauknya tempe orek sama telur dadar", "Neutral"),
("Beli pulsa 100rb dapet kuota berapa GB ya skrg?", "Neutral"),
("Jam berapa bioskop XXI di Margo City buka?", "Neutral"),
("Mau nanya dong, STNK mati setahun dendanya berapa?", "Neutral"),
("Aturan baru ganjil genap itu berlaku weekend juga ga sih?", "Neutral"),
("Ada yg tau cara reset password wifi IndiHome?", "Neutral"),
("Baru sadar kalo hari ini udah tanggal 15 doang, kirain udah akhir bulan", "Neutral"),
("Ada yg tau merk AC hemat listrik yg bagus?", "Neutral"),
("Lagi nyari tukang servis kulkas panggilan murah di daerah Depok", "Neutral"),
("Tadi pagi liat antrian di ATM panjang, pdhl jam 7", "Neutral"),
("Buat yg WFH, biasanya abis kerja ngapain?", "Neutral"),
("Lagi belajar bikin CV yg ATS friendly", "Neutral"),
("Ada yg tau email pengaduan buat PDAM?", "Neutral"),
("Cuci motor di deket komplek harganya 25rb, mahal apa wajar?", "Neutral"),
("Ada yg nyariin tim futsal buat fun game minggu ini?", "Neutral"),
("Kenapa ya printer gw kertasnya sering nyangkut?", "Neutral"),
("Apakah bener charger HP merk X bisa dipake buat semua HP?", "Neutral"),
("Ada yg punya jadwal lengkap KRL Bogor - Jakarta?", "Neutral"),
("Lagi ngantri di apotek buat ambil obat resep dokter", "Neutral"),
("Kompor gas gw nyalanya kecil, udah dibersihin masih gitu", "Neutral"),
("Mau nyoba jualan kosmetik, modal awalnya berapa ya?", "Neutral"),
("Ada rekomendasi klinik gigi murah di Tangerang?", "Neutral"),
("Tumbler stainless steel yg bagus itu merk apa ya?", "Neutral"),
("Penghasilan kena pajak minimal brp ya skrg?", "Neutral"),
("Baru download Threads, kok sepi ya beda sama X", "Neutral"),
("Lagi isi form lamaran kerja, ada kolom expected salary", "Neutral"),
("Baterai laptop gw cepet abis padahal baru beli setahun", "Neutral"),
("Ada yg punya rekomendasi powerbank awet buat traveling?", "Neutral"),
("Tumbler yg bisa nyimpen panas 12 jam itu beneran ada?", "Neutral"),
("Kalian rata2 tidur jam berapa?", "Neutral"),
("Tadi ngeliat truk gandeng nyangkut di gang sempit", "Neutral"),
("Lagi browsing harga laptop second buat anak kuliah", "Neutral"),
("Tumben banget jalan Sudirman pagi ini ga macet", "Neutral"),
("Mau pesen tiket kereta lebaran, udah dibuka belum ya?", "Neutral"),
("Ada yg tau harga pasaran motor matic sekarang?", "Neutral"),
("Lagi nonton video tutorial cara ganti ban motor sendiri", "Neutral"),
("Bubur ayam langganan gw tutup, mungkin libur", "Neutral"),
("Jam weker bunyi, snooze, bangun kesiangan lagi", "Neutral"),
("Ngafe sendirian sambil ngerjain tugas, vibesnya enak", "Neutral"),
("Lagi nunggu antrian di bank, nomor antrian 147", "Neutral"),
("Baru sadar hari ini belom minum air putih sama sekali", "Neutral"),
("Ada yg ngerti cara upload dokumen di aplikasi ini?", "Neutral"),
("Pesanan di marketplace udah dari kemarin statusnya packed doang", "Neutral"),
("Lagi belajar masak dari video YouTube, bahannya banyak yg ga ada", "Neutral"),
("Kacamata gw pecah, mau bikin yg baru tapi bingung modelnya", "Neutral"),
("Ngeliatin kucing berantem di genteng, seru juga", "Neutral"),
("Buka warung makan jam berapa ya biasanya rame?", "Neutral"),
("Ada rekomendasi kursus mengemudi yg bagus?", "Neutral"),
("Motor gw ada bunyi aneh di roda depan, bahaya ga ya", "Neutral"),
("Lagi nyari tempat potong rambut cowo yg murah tapi rapi", "Neutral"),
("Tadi lihat ada pak pos antar paket, pas hujan pula", "Neutral"),
("Abis ngepel lantai 2 jam, eh ujan lagi... bye bye kinclong", "Neutral"),
("Mau ngeganti oli mobil, bengkel resmi atau biasa aja ya", "Neutral"),
("Cek notifikasi hape, isinya promo doang ga ada yg penting", "Neutral"),
("Buka rekening bank baru, ternyata syaratnya banyak", "Neutral"),
("Ada tetangga lagi renovasi rumah, berisik dari pagi", "Neutral"),
("Notifikasi email 200+ unread, males bukanya", "Neutral"),
("Lagi nyari jadwal imsakiyah buat puasa senin kamis", "Neutral"),
("Pergi ke pasar beli sayur, nawar2 dulu", "Neutral"),
("Hape lowbat di 5 persen, charger ketinggalan di rumah", "Neutral"),
("Tadi pagi jalan kaki 30 menit, lumayan buat olahraga", "Neutral"),
("Sedang browsing GPU bekas buat upgrade PC", "Neutral"),
("Baru nyobain fitur baru di X buat bikin thread panjang", "Neutral"),
("Sudah mau maghrib, waktunya tutup laptop dan istirahat", "Neutral"),
("Ada yg tau cara bedain oli palsu sama oli asli?", "Neutral"),
("Lagi mikir mau jualan apa yg laku di musim hujan gini", "Neutral"),
("Tadi liat ada orang jualan es doger, jadi nostalgia jaman SD", "Neutral"),
("Besok meeting jam 8 pagi, harus tidur lebih awal", "Neutral"),
("Ada yg pernah coba kirim motor lewat cargo?", "Neutral"),
("Lagi nonton video anak2 main layangan di lapangan", "Neutral"),
("Cek saldo rekening... aman, masih cukup buat sebulan", "Neutral"),
("Beli gorengan di depan gang, tahu isi sama tempe mendoan", "Neutral"),
("Charger laptop rusak, harus beli baru padahal mahal", "Neutral"),
("Nemu akun X yg isinya thread2 sejarah, menarik juga", "Neutral"),
("Hari ini pakai baju warna biru, kebetulan aja", "Neutral"),
("Pesen es teh manis di warung, tapi lupa bilang kurang manis", "Neutral"),
("Mau nanya, BPJS Kesehatan masih bisa dipake di RS swasta ga?", "Neutral"),
("Setiap sore lewat depan sekolah, ada anak2 latihan futsal", "Neutral"),
("Lagi denger podcast sambil nunggu hujan reda", "Neutral"),
("Udah saatnya servis AC, udah setahun ga dibersihin nih", "Neutral"),
("Tadi siang liat ada bapak2 bawa tanaman bonsai, keren", "Neutral"),
("Perbedaan teh tubruk sama teh celup itu apa sih sebenernya?", "Neutral"),
("Lagi download file besar, koneksi stabil di 2MB/s", "Neutral"),
("Ada yg pernah ikut tour wisata sejarah Jakarta?", "Neutral"),
("Lagi cek harga emas hari ini, naik atau turun ya?", "Neutral"),
("Mau beli sepatu running, rekomendasi merk yg awet dong", "Neutral"),
("Tadi siang ke minimarket, beli sabun sama sampo", "Neutral"),
("Besok jadwal donor darah di kantor kecamatan", "Neutral"),
("Jam berapa ya penerbangan Jakarta Surabaya yg paling pagi?", "Neutral"),
("Lagi mikir mau daftar S2 atau kerja dulu ya", "Neutral"),
("Ada yg tau tarif tol Jakarta Bandung sekarang?", "Neutral"),
("Lagi ngantri di Samsat buat bayar pajak tahunan", "Neutral"),
("Cuaca mendung dari siang, mungkin nanti sore hujan", "Neutral"),
("Besok ada webinar gratis tentang financial planning", "Neutral"),
("Lagi bersihin file2 ga penting di laptop, lumayan hemat 20GB", "Neutral"),
("Siapa tau ada yg jual laptop second murah tapi spek oke?", "Neutral"),
("Mau tanya, ganti ban motor sepasang habis berapa ya?", "Neutral"),
("Ada yg tau harga tiket masuk Dufan sekarang?", "Neutral"),
("Lagi nyari apartemen deket stasiun, budget 2jt per bulan", "Neutral"),
("Tadi liat ada pameran tanaman hias di mall, rame banget", "Neutral"),
("Lagi bingung milih ISP, antara First Media atau Biznet", "Neutral"),
("Ada yg tau restoran India yg authentic di Jakarta?", "Neutral"),
("Baru nemu podcast sejarah Indonesia yg dibawain dengan gaya storytelling", "Neutral"),
("Buka aplikasi Gojek, liat promo, close lagi. masih gajian minggu depan", "Neutral"),
("Kenapa ya sinyal provider A di daerah gw lemah bgt kalo malem?", "Neutral"),
("Lagi nyari printer murah buat ngeprint dokumen kantor di rumah", "Neutral"),
("Besok jadwal servis mobil rutin tiap 10rb km", "Neutral"),
("Ada yg tau tempat tes PCR murah di Jakarta Pusat?", "Neutral"),
("Lagi browsing resep masakan simple buat anak kos", "Neutral"),
("Cek resi pengiriman, statusnya masih di transit hub", "Neutral"),
("Ada yg tau film yg lagi tayang di bioskop XXI?", "Neutral"),
("Lagi hitung budget renovasi kamar mandi, kayaknya mahal deh", "Neutral"),
("Kemarin liat iklan HP baru, jadi pengen ganti tapi masih sayang", "Neutral"),
("Besok mau ke Dufan bareng keluarga, semoga ga ujan", "Neutral"),
("Ada yg nyari jasa fotokopi murah deket kampus UI?", "Neutral"),
("Lagi cari kerja remote sebagai content writer, ada info?", "Neutral"),
("Tadi pagi lihat ada kecelakaan kecil di depan pasar", "Neutral"),
("Baterai HP udah 2 tahun, harus ganti tapi males ke service center", "Neutral"),
("Ada yg tau kapan pemilu legislatif berikutnya?", "Neutral"),
("Mau nyobain mie level pedes yg lagi viral, cabangnya dimana ya?", "Neutral"),
("Lagi iseng liat2 properti di apps, sapa tau ada yg murah", "Neutral"),
("Ada yg ngerti cara lapor SPT tahunan online?", "Neutral"),
("Tadi ada gempa kecil, berasa goyang dikit doang", "Neutral"),
("Jam pulang kantor, macet lagi di Tol Dalam Kota", "Neutral"),
("Lagi mikir mau jual motor atau dipertahanin buat investment", "Neutral"),
("Penjual es keliling lewat, jadi pengen es campur", "Neutral"),
("Lagi nonton video DIY rakitan meja dari kayu palet", "Neutral"),
("Ada yg tau komunitas lari di Gelora Bung Karno?", "Neutral"),
("Lagi di angkringan, pesen kopi jos sama sate usus", "Neutral"),
("Lagi bersihin keyboard mekanik, debunya numpuk parah", "Neutral"),
("Mau nanya, gimana cara claim asuransi kendaraan?", "Neutral"),
("Ada yg punya template surat lamaran kerja yg ATS friendly?", "Neutral"),
("Lagi belajar edit video pake CapCut dari YouTube tutorial", "Neutral"),
("Besok waktunya timbangan mingguan, hopefully turun lagi", "Neutral"),
("Tadi liat antrian panjang banget di konter hape", "Neutral"),
("Nemu artikel cara menabung 10jt dalam setahun, seems doable", "Neutral"),
("Lagi cek jadwal KRL, ada perbaikan jalur katanya", "Neutral"),
("Mau pesen kopi online, tapi males kalo harus nunggu lama", "Neutral"),
("Ada yg pernah ikut kelas yoga online? rekomendasi dong", "Neutral"),
]
# Ensure exactly 500
sentiment_data = sentiment_data[:500]

df_sentiment = pd.DataFrame(sentiment_data, columns=["text", "label"])
df_sentiment.to_excel(f"{out}/sentiment_dataset.xlsx", index=False)
print(f"Sentiment: {len(df_sentiment)} samples - {df_sentiment['label'].value_counts().to_dict()}")

print("Done!")
